# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Blog
email: blank@blank.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for Jay to be able to write about various things he likes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://appreciat.es" # the base hostname & protocol for your site
twitter_username: mechaspam
github_username:  jalev

# Build settings
markdown: kramdown
